name: Lint and Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-bandit:
    name: Run Flake8 and Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # or match your project’s version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Run Flake8 (Linting)
        run: |
          echo "Running flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Bandit (Security Scan)
        run: |
          echo "Running bandit..."
          bandit -r . -ll
